<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("noindex", "Y");
$APPLICATION->SetTitle("Публичная оферта");
?>
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Соглашение о предоставлении услуг сервисом </span></b><b><span lang="EN-US" style="line-height: 115%; background: white;">shopograd</span></b><b><span style="line-height: 115%; background: white;">.</span></b><b><span lang="EN-US" style="line-height: 115%; background: white;">ru</span></b><b><span style="line-height: 115%; background: white;"><o:p></o:p></span></b></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">&laquo;Шопоград Инк&raquo; (</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;"> </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Inc</span><span style="font-size: 10pt; line-height: 115%; background: white;">), зарегистрированное по адресу: 3А, Лител Денмарк Комплекс,  майн стрит, , город. Роуд Таун 4473, остров Тортола, Британские Виргинские острова., далее &mdash; «Исполнитель», и дееспособное физическое лицо, регистрирующееся на Интернет-сайте </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">.</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">ru</span><span style="font-size: 10pt; line-height: 115%; background: white;">, далее — «Покупатель», заключают следующее соглашение:<o:p></o:p></span></font></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">1. Определение терминов.<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Сайт</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — Интернет-ресурс под доменным именем </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">&reg;, администрируемый Исполнителем.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Покупатель</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — физическое дееспособное лицо, добровольно прошедшее Регистрацию и заказывающее указанные в разделе 2 Соглашения Услуги с доставкой по адресу, который обслуживается Исполнителем.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Интернет-сервис (</span></b><b><span lang="EN-US" style="line-height: 115%; background: white;">Shopograd</span></b><b><span style="line-height: 115%; background: white;">®)</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — администрируемый Исполнителем программный комплекс, доступ к которому пользователи Сайта получают посредством интерфейса Сайта, предоставляющий пользователям следующие функциональные возможности:<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- просматривать информацию о Товарах и другие сведения, материалы, размещенные Исполнителем на Сайте;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- отбирать интересующие Товары (выкладывать в «Корзину»);<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- проходить Регистрацию, Авторизацию;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- размещать заказы;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">и другие.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Товар</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — продукция, предлагаемая к продаже в интернет-магазине TAOBAO.COM (</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">®) с описанием на китайском языке, информация о которой представлена на Сайте на русском языке.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Регистрация</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — процедура, в ходе которой Покупатель посредством Интернет-сервиса предоставляет Исполнителю информацию, необходимую для оказания Услуг. Регистрация считается завершенной только в случае успешного прохождения всех ее этапов в соответствии с опубликованными на Сайте инструкциями. Персональные данные при Регистрации не запрашиваются и не предоставляются. По итогам Регистрации создается учетная запись Покупателя, лицевой счет и личный кабинет. Сообщенная при регистрации информация может быть впоследствии изменена Покупателем. Если в течение 365 дней с даты регистрации покупатель не разместил заказ и не оплатил его, регистрационные данные удаляются с Сайта.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Авторизация</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — сообщение Покупателем Исполнителю своей регистрационной информации посредством Сайта.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Личный кабинет</span></b><span style="line-height: 115%; background: white;"> </span><span style="font-size: 10pt; line-height: 115%; background: white;">— персональный и не доступный третьим лицам раздел Сайта, доступ к которому осуществляется Покупателем путем ввода личных логина — имени доступа и пароля — кода доступа, и который содержит информацию о заказах Покупателя, их оплате и исполнении и состоянии лицевого счета, а также предоставляет функциональную возможность удаленного взаимодействия Сторон при исполнении Соглашения.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Заказ</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — заявка, переданная Покупателем Исполнителю через интерфейс Сайта, содержащая перечень Товаров, которые Покупатель просит Исполнителя приобрести и отправить Покупателю на условиях Соглашения, и сведения, необходимые для доставки Товаров.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><b><span style="line-height: 115%; background: white;">Лицевой счет</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"> — персональный счет Покупателя (учетная запись), отражающий данные автоматизированной системы учета Исполнителя о совершении платежей по настоящему Соглашению и данные об остатке денежных средств Покупателя, перечисленных Исполнителю, в режиме реального времени.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">2. Общие положения<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">2.1. Исполнитель предоставляет Покупателю посреднические услуги по покупке и по заказу в интересах Покупателя Товаров в интернет-магазине TAOBAO.COM (</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">®) — далее «Услуги», на условиях данного Соглашения.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">2</span><span style="font-size: 10pt; line-height: 115%; background: white;">.1.1. Исполнитель обязуется по поручению Покупателя за вознаграждение совершить одну или несколько сделок от своего имени, но за счет Покупателя.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">По сделке, совершенной Исполнителем с третьим лицом, приобретает права и становится обязанным Исполнитель, хотя бы Покупатель и был назван в сделке или вступил с третьим лицом в непосредственные отношения по исполнению сделки.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">2.1.2. Услуги Исполнителя включают:<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">- обеспечение функционирования Интернет-сервиса </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">®, посредством которого Покупатель осуществляет заказ Товаров и Услуг и получает информацию о ходе исполнения Исполнителем заказа (оказания Услуг);<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">- закупка заказанных Покупателем Товаров у производителей, чьи товары предлагаются в интернет-магазине TAOBAO.COM (</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;"> </span><span style="font-size: 10pt; line-height: 115%; background: white;">®), обработка и отправка посылок в адрес Покупателя на условиях Соглашения;<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">- предоставление консультаций по использованию Интернет-сервиса </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;"> </span><span style="font-size: 10pt; line-height: 115%; background: white;">по телефону «горячей линии» на русском языке и посредством использования возможностей Сайта.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">2.2. Услуги предоставляются Покупателю с использованием Интернет-сервиса </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">®. Для получения Услуг Покупателю необходимо пройти регистрацию на Сайте и оформить заказ Товара(-ов) и Услуг.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">2.3. За оказание Услуг Исполнитель удерживает с Покупателя комиссионное вознаграждение, включенное в стоимость Товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">2.4. Соглашение является публичной офертой, которая содержит предложение Исполнителя заключить договор на указанных в настоящем документе условиях с любым лицом, отвечающим требованиям Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">2.5. Исполнитель оставляет за собой право вносить изменения в настоящее Соглашение, в связи с чем Покупатель обязуется регулярно отслеживать изменения в Соглашении, размещенном по адресу http://www.shopograd.ru/o-shopograde/publichnaya-oferta/.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">2.6. Дополнительная информация о порядке оказания Услуг Исполнителем и использования Покупателем Интернет-сервиса опубликована Исполнителем на Сайте. Если информация, опубликованная на Сайте, противоречит положениям настоящего Соглашения, применяются условия Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">3. Оформление заказа<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">3.1. Для получения Услуг Покупатель самостоятельно проходит регистрацию на Сайте. Исполнитель не несет ответственности за достоверность данных, указанных Покупателем при регистрации и заказе Товара и невозможность оказания Услуг вследствие сообщения Покупателем недостоверных сведений о себе (в этом случае оплаченные Покупателем Исполнителю суммы не возвращаются). Регистрация на сайте включает в себя запрос персональных данных Покупателя, защита которых производится в соответствии с Политикой Безопасности, опубликованной на сайте — </span><b><span style="font-size: 14pt; line-height: 115%; background: white;">внести пункт меню и сделать ссылку</span></b><span style="font-size: 10pt; line-height: 115%; background: white;"><o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.2. Оформление заказа производится Покупателем самостоятельно через личный кабинет. Покупатель осуществляет выбор Товара на Сайте и помещает его в Корзину. Покупатель до начала оформления заказа может самостоятельно удалять и добавлять Товары в Корзине, оформление заказа производится в соответствии с указаниями, опубликованными на Сайте. Информация об оформленных заказах доступна Покупателю в личном кабинете.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Зарегистрированный Покупатель может авторизоваться на Сайте (зайти на сайт под своими учетными данными). Неавторизованный Покупатель, делающий заказ посредством Сервиса впервые, может просматривать текстовые страницы Сайта, а также страницы каталога Товаров, может выкладывать Товары в «Корзину». Может просматривать содержимое своей Корзины, добавлять или удалять Товары, а также изменять их количество. После нажатия кнопки «Оформить заказ» Покупатель попадает на страницу регистрации, где Сервис предлагает неавторизованному Покупателю пройти Регистрацию, а зарегистрированному — авторизоваться.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Неавторизированный пользователь может добавить в корзину не более 50 товаров. Хранение товаров в корзине неавторизированного пользователя не осуществляется.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Авторизированный пользователь может добавить в Корзину до 150 товаров. Данные о товарах, добавленных в Корзину авторизированным пользователем, сохраняются в течение 45 дней с даты добавления последнего товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">По истечении 45 дней Корзина авторизированного покупателя очищается.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.3. В заказе должны быть указаны:<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">а) имя, отчество и фамилия Покупателя и адрес доставки;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">б) наименование Товара, артикул, марка, цвет, размер, количество предметов, входящих в комплект приобретаемого Товара, цена Товара;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">в) рассчитанный Покупателем самостоятельно вес Товара;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">г) по желанию Покупателя — контактный телефон и иная информация из предложенной для заполнения формы, а также комментарии Покупателя к заказу.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель вправе хранить сообщенную Покупателями при оформлении заказов информацию в своей электронной базе данных в течение неограниченного срока в целях использования такой информации для оформления повторных заказов, получения статистической информации и информирования Покупателей о деятельности Исполнителя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.4. Заказ может быть отменен, изменен или дополнен Покупателем полностью или частично в любое время до момента совершения Покупателем оплаты. После оплаты заказа внесение изменений в заказ (отмена товаров, изменение свойств товаров) не производится. Добавление Товаров в оплаченный заказ возможно в течение 30 дней с момента оформления заказа (если иные сроки не предусмотрены условиями маркетинговых акций), до момента подтверждения отправки заказа, при добавлении Товаров к заказу после его формирования сроки оказания Услуг отсчитываются заново от даты добавления последнего Товара в заказ.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.5. Заказы на оказание Услуг принимаются Исполнителем с помощью Сервиса круглосуточно 7 дней в неделю, оказание Услуг производится в рабочие дни, официально установленные в Китае, «горячая линия» в Москве работает согласно расписанию, опубликованному на Сайте.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.6. Исполнитель не гарантирует постоянное присутствие выбранного Покупателем Товара в каталоге Товаров на Сайте и обязуется проинформировать Покупателя об отсутствии в каталоге Исполнителя заказанного Товара. В случае отсутствия заказанных Товаров на складе поставщика Исполнитель вправе удалить указанный Товар из заказа Покупателя и уведомить об этом последнего путем направления электронного сообщения по адресу, указанному при регистрации (либо через личный кабинет) в течение 5 (пяти) рабочих дней с момента оплаты Покупателем заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.7. Исполнитель не гарантирует Покупателю наличие у поставщика (возможность приобретения) заказываемого Товара, а также наличие выбранной размерности, цвета и комплектности Товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.8. Покупатель должен дополнительно оплатить стоимость доставки Товара исходя из веса Товара, рассчитав его самостоятельно при формировании заказа, основываясь на данных о среднем весе Товара, указанном в карточке Товара поставщиком. Если вес Товара поставщиком не указан, Покупатель может воспользоваться справочной информацией по весу Товаров, представленной на Сайте, либо в любых других независимых источниках по собственному усмотрению. В случае если сумма оплаты за заказ не покрывает стоимость Товара, оплаченную поставщикам, и стоимость доставки Товара до Покупателя, через 90 дней с даты подтверждения отправки заказа поручение считается отмененным Покупателем, в этом случае стоимость Товаров и Услуг Исполнителя Покупателю не возвращается, Исполнитель возвращает Покупателю денежные средства, оплаченные за доставку Товаров.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.9. При формировании заказа Покупатель указывает размеры в соответствии с информацией о Товаре, указанной поставщиком, а в некоторых случаях также цвет Товара и дополнительные характеристики. Исполнитель не несет ответственности за достоверность представленной поставщиком в описании Товара информации по размерности, цвету и качеству и другим параметрам.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.10. До оформления заказа Покупатель обязуется ознакомиться с перечнем товаров, запрещенных к пересылке почтовыми службами страны Покупателя и с условиями таможенного оформления товаров, заказанных в интернет-магазинах.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.11. Покупатель самостоятельно несет ответственность за соответствие приобретаемого им Товара условиям доставки почтовой службы и таможенному кодексу страны, в которой находится Покупатель, включая, но не ограничиваясь габаритами, весом и содержанием Товара, включая габариты и вес почтовой тары, необходимой для пересылки Товара Покупателю почтовой службой.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.12. После оформления заказа Покупатель вносит 100% предварительную оплату в размере стоимости Товаров, Услуг Исполнителя и предварительно рассчитанной Покупателем при оформлении заказа стоимости доставки Товаров Покупателю. Момент получения Исполнителем оплаты по заказу считается моментом акцепта оферты Покупателем и заключения договора между Покупателем и Исполнителем в отношении исполнения соответствующего заказа на условиях настоящего Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">3.13. В случае полного или частичного отказа Покупателя от заказа после его оплаты (расторжение договора по инициативе Покупателя) Исполнитель имеет право удержать с Покупателя стоимость заказанных Товаров, которые невозможно вернуть поставщикам, услуг по их доставке и/или иных произведенных Исполнителем для выполнения поручения Покупателя расходов. Таким образом, если Товар находится в статусе «Заказан» или «Готов к отправке», удалить его из заказа или отменить поручение без согласования с Исполнителем невозможно.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">4. Оплата<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.1. Оплата заказа возможна способами, указанными на Сайте в разделе «Оплата» по адресу: http://www.shopograd.ru/pomoshch/oplata-i-dostavka/.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.2. Если фактическая цена Товара будет отлична от цены, заявленной поставщиком на момент оформления заказа Товара Покупателем, Исполнитель при первой возможности информирует об этом Покупателя для подтверждения либо удаления из заказа данного Товара. При невозможности связаться с Покупателем заказ на покупку данного Товара считается аннулированным.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.3. Исполнитель не кредитует Покупателей, не выкупает Товары в долг, не отправляет посылки в долг.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.4. При оплате на счет Исполнителя в Великобритании или Китае Покупатель дополнительно оплачивает комиссию банка Исполнителя. Комиссии банков-посредников также обязан оплачивать Покупатель.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.5. Если доставка по Китаю или другой стране бесплатная для определенной суммы/стоимости заказанных товаров, но впоследствии из этой оплаченной группы товаров будет удален хотя бы один товар (например по причине его отсутствия), в результате чего сумма/стоимость уменьшится ниже порогового значения, то доставка становится платной и подлежит оплате Покупателем (в частности, при наличии средств на лицевом счете списывается с лицевого счета Покупателя).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.6. Если оплата заказа не произведена в течение 10 дней после оформления заказа, заказ считается отмененным Покупателем и удаляется из личного кабинета. Если в указанный срок произведена частичная оплата, то Покупателю предоставляется 90-дневный срок для осуществления оплаты в полном объеме. Не оплаченный в течение 90 дней заказ считается отмененным Покупателем, и Исполнитель зачисляет полученные в счет оплаты такого заказа денежные средства на лицевой счет Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.7. В случае, если сумма оплаты за заказ не покрывает полностью стоимость Товара, уплаченную Исполнителем поставщикам, стоимость Услуг Исполнителя и стоимость доставки Товара до Покупателя, через 90 дней с даты подтверждения отправки заказа поручение считается отмененным Покупателем. В этом случае стоимость Товаров и Услуг Исполнителя Покупателю не возвращается, Исполнитель возвращает Покупателю денежные средства, оплаченные за доставку Товаров. Товары, приобретенные по данному поручению, переходят в собственность Исполнителя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">4.8. Покупатель вправе вывести остаток денежных средств на свою банковскую карту из системы со своего лицевого счета после завершения всех заказов. Выводу подлежат только фактические остатки денежных средств, внесенных клиентом. Возврат денежных средств осуществляется в рублях по курсу ЦБ РФ на дату зачисления. Переводы с других лицевых счетов при этом выведены быть не могут. В целях безопасности, в соответствии с законодательством РФ для совершения операции по возврату денежных средств с лицевого счета покупателю необходимо пройти упрощенную идентификацию. Для этого нужно авторизоваться и заполнить специальную форму для обращения в службу поддержки в категории «Возврат денег».<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5. Исполнение заказа. Закупка Товаров у поставщиков<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.1. После поступления оплаты согласно п.3.12 раздела 3 Соглашения Исполнитель приступает к оказанию Услуг по исполнению заказа, что включает в себя закупку Товаров у китайских поставщиков, доставку на склад Исполнителя в Китае, консолидацию Товаров в одну посылку, упаковку, проверку качества (в пределах, установленных Соглашением), взвешивание и отправку Товаров Исполнителю через службу доставки из списка, опубликованного на Сайте. Если габариты или вес Товаров превышают установленные почтовыми службами ограничения либо количество или свойства Товаров не позволяют их отправить в одной посылке, то Товары распределяются Исполнителем на несколько посылок, о чем Исполнитель информирует Покупателя через личный кабинет.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Если габариты или вес Товаров превышают допустимые и товар является неделимым, Исполнитель имеет право отказать Покупателю в поставке товаров.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Закуп товара у продавца производится в срок до 3 рабочих дней с момента оплаты заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Срок поставки Товара от Продавца на склад Исполнителя зависит от условий работы Продавца. Контрольный срок поставки Товара на склад Исполнителя составляет 14 рабочих дней с даты закупа Товара у Продавца.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель уведомляет Покупателя, если срок поставки товара превышает 14 рабочих дней и закупает товары с более длительным сроком поставки после подтверждения от Покупателя в личном кабинете.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель имеет право в одностороннем порядке отменить Товар в случае, если срок поставки превысит 14 дней. Исполнитель производит упаковку и взвешивание Заказа в течение 3 рабочих дней с даты поступления последнего товара на склад Исполнителя. Передача Заказа на доставку почтовым службам осуществляется в течение 2 рабочих дней с момента взвешивания заказа, при условии полной оплаты Заказа. В случае, если после взвешивания Заказа необходима оплата доставки, Заказ передается на доставку в течение 2 рабочих дней после поступления оплаты.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">В случае добавления новых Товаров в Заказ, сроки его обработки отсчитываются заново от даты оплаты последнего добавленного товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">В случае внесения по согласованию с Покупателем изменений в перечень Товаров или условия их доставки срок оказания Услуг увеличивается, о чем Исполнитель информирует Покупателя через личный кабинет.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Если Исполнитель не проинформировал Покупателя о готовности заказа к отправке по истечении 30 дней после оплаты заказа и не согласовал с Покупателем отсрочку в исполнении заказа, Покупатель имеет право по своему усмотрению потребовать уменьшения цены за оказание Услуги или отказаться от Товара, потребовав возврата уплаченной суммы. Покупатель также вправе потребовать у Исполнителя полного возмещения убытков.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Средний срок обработки заказа от момента получения оплаты до момента передачи посылки на отправление составляет от 6 до 14 рабочих дней. В случае внесения по согласованию с Покупателем изменений в перечень Товаров или условия их доставки срок оказания Услуг увеличивается, о чем Исполнитель информирует Покупателя через личный кабинет.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.2. Исполнитель обязуется заключить договор(-ы) купли-продажи заказанных Покупателем Товаров с поставщиком(-ами) Товара и оплатить заказанные Покупателем Товары поставщикам от своего имени, но за счет Покупателя при условии, что данный поставщик осуществляет доставку товаров до офиса (склада) Исполнителя в Китае.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.3. Информация о стадиях исполнения заказа, а также о необходимых для продолжения оказания Услуг действиях Покупателя предоставляется Покупателю Исполнителем через личный кабинет.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.4. В случае если поставщик Товара не соблюдает заявленные сроки поставки, вследствие чего задерживается выполнение заказов Покупателя, Исполнитель вправе удалить указанный Товар из заказа Покупателя и уведомить об этом последнего путем направления электронного сообщения по адресу, указанному при регистрации (либо через личный кабинет).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.5. В случае поставки на склад Исполнителя в Китае некачественного Товара, последний по своему усмотрению может отказаться от Товара или согласовать с Покупателем возможность доставки Товара Покупателю.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">В случае поставки на склад Исполнителя товара в количестве, меньшем чем было заказано, последний вправе изменить количество товара на фактически полученное от Продавца товара без согласования с Покупателем.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.6. В случае если заказанный Товар не может быть поставлен в страну, указанную Покупателем, вследствие действующих ограничений на пересылку товаров почтовыми службами, Исполнитель вправе удалить товар из заказа Покупателя и уведомить об этом последнего путем направления электронного сообщения по адресу, указанному при регистрации (либо через личный кабинет).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.7. Исполнитель обязуется принять Товар, доставленный поставщиком, на свой склад.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.8. Исполнитель обязуется проверить соответствие доставленных поставщиками Товаров указанным в заказе характеристикам (наименование/артикул, количество, размер, цвет, наличие на Товаре признаков бывшего/не бывшего в употреблении) согласно сопроводительной информации к Товарам, принимая во внимание возможность нарушения цветопередачи в изображении Товара на Сайте.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель обязуется при возможности удостовериться в работоспособности Товара (например, загорание сигнала «включен» при включении бытового электрооборудования в электросеть).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель обязуется удостовериться в отсутствии явных видимых дефектов, повреждений Товара и явного несоответствия доставленных Товаров описанию на Сайте (например, сумка из льна вместо сумки из кожи).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Исполнитель не принимает на себя никакие иные обязательства по проверке соответствия доставленных поставщиками Товаров и их качества Товарам, заказанным Покупателем. Исполнитель не проверяет товар, полученный от поставщика, на соответствие заявленным поставщиком характеристикам и в случае ошибки поставщика не несет ответственности за несоответствие Товара условиям заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.9. В случае выявления несоответствия Товара заказу Покупателя Исполнитель по своему усмотрению вправе отказаться от Товара и удалить его из заказа либо согласовать с Покупателем возможность поставки ему Товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.10. Исполнитель обязуется сообщать Покупателю информацию о выявленных при комплектации посылки явных дефектах Товара посредством личного кабинета.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.11. Исполнитель обязуется сформировать посылку с Товарами по каждому заказу отдельно и упаковать полученные на склад Товары согласно обычаям делового оборота, требованиям службы доставки и инструкциям Покупателя, указанным при формировании заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.12. Отправка Товаров Покупателю осуществляется после подтверждения отправки Покупателем через личный кабинет, при этом максимальный срок для подтверждения отправки &ndash; 36 часов с момента информирования Исполнителем Покупателя о готовности заказа к отправке через личный кабинет (в случае нарушения этого срока отправка считается подтвержденной Покупателем, Сервис автоматически генерирует подтверждение отправки в личном кабинете).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">5.13. В случае указания Покупателем ошибочных данных для доставки Товара Исполнитель имеет право на возмещение понесенных расходов по доставке и возврату Товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">6. Формирование Посылки и Доставка товаров<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">6.1. Доставка посылок с Товарами осуществляется способами и по тарифам, указанным в разделе «Доставка» </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">® по адресу http://www.shopograd.ru/pomoshch/oplata-i-dostavka/.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.2. Если в заказе Покупателя находятся товары, запрещенные к авиаперевозке, Исполнитель вправе отправить их способом доставки China Post АВТО или курьерской доставкой, уведомив об этом Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.3. Оплата доставки Товаров Покупателя производится отдельно от оплаты самих Товаров и Услуг Исполнителя. Окончательная стоимость доставки Товаров до Покупателя сообщается Исполнителю службой доставки после того, как посылка упакована и взвешена. После упаковки Исполнитель не вскрывает упакованные посылки. В случае нехватки денежных средств на лицевом счете Покупателя передача посылки для отправки в службу доставки будет задержана до оплаты Покупателем стоимости доставки.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.4. В случае, если срок хранения готового к отправке и не оплаченного на 100% Покупателем заказа превысит 30 календарных дней, Исполнитель взимает плату за хранение в размере 1$ в сутки за каждый килограмм заказа, начиная с 31-го дня хранения. Отправка несвоевременно оплаченных заказов производится Исполнителем только после погашения долга и оплаты стоимости услуг по хранению. Через 90 дней хранения готового к отправке и не оплаченного на 100% заказа поручение считается отмененным Покупателем, в этом случае стоимость Товаров и Услуг Исполнителя Покупателю не возвращается, Исполнитель возвращает Покупателю денежные средства, оплаченные за доставку Товаров. Покупатель информируется об изменении статуса соответствующего заказа через личный кабинет.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.5. Исполнитель обязуется передать упакованную посылку с Товарами Покупателя почтовой службе, которую Покупатель указал в деталях заказа в личном кабинете.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.6. Услуги считаются полностью оказанными Исполнителем с момента передачи надлежащим образом упакованной и оформленной посылки с Товарами Покупателя почтовой службе.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">6.7. Исполнитель не отвечает за действия почты, курьерских служб и транспортных компаний и не может влиять на скорость доставки. Указанные на Сайте </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">® сроки доставки являются приблизительными.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">6.8. В случае, если посылка с заказом не востребована Покупателем или Покупатель отказался от получения посылки, стоимость заказа не возмещается. Возможна повторная отправка посылки после ее возвращения Исполнителю. Повторная отправка осуществляется после оплаты Покупателем почтовых услуг по возврату посылки к Исполнителю и оплаты повторной доставки. В случае, если в течение 30 дней с момента возврата посылки Исполнителю Покупатель не оплатит повторную доставку, посылка утилизируется, стоимость товаров не возмещается.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">7. Другие обязанности и права Исполнителя<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.1. Исполнитель обязуется выполнять требования Покупателя, связанные с выполнением Услуг, если такие требования не противоречат данному Соглашению, а также информации, опубликованной на Сайте. В случае предъявления Покупателем требований, связанных с устранением недостатков оказанной Услуги (например, об уменьшении цены Услуги, повторном оказании Услуги), Исполнитель обязуется удовлетворять такие требования в течение 15 рабочих дней, не считая сроки доставки заказа службой доставки и/или время проведения банковских операций и/или сроки выполнения третьими лицами действий, необходимых для выполнения Исполнителем своих обязательств.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.2. Исполнитель обязуется сохранять конфиденциальность предоставленных Покупателем данных и не разглашать их третьим лицам (за исключением уполномоченных государственных органов, а также аудиторов, консультантов, бухгалтеров, юристов на условиях сохранения ими конфиденциальности полученной информации), если это не требуется для выполнения условий данного Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.3. Исполнитель обязуется предоставлять Покупателю информацию о выполнении поручений, указанных в данном Соглашении.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.4. Исполнитель обязуется осуществлять защиту учетной записи Покупателя от неправомерного доступа, уничтожения размещенной Покупателем информации, а также от иных неправомерных действий в отношении такой информации всеми находящимися в его распоряжении техническими средствами, при этом не гарантируя достаточность примененных технических средств для предотвращения вредоносных действий третьих лиц.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.5. Исполнитель оставляет за собой право размещать на Сайте либо направлять на предоставленный Покупателем электронный адрес рекламные и информационные сообщения в связи с деятельностью Исполнителя (кроме сообщений, связанных с обработкой заказа), при этом Исполнитель обязуется прекратить отправку Покупателю сообщений по электронной почте в случае получения по электронной почте заявления Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.6. Исполнитель предоставляет Покупателям консультации/техническую поддержку по запросу Покупателя, сделанному по телефону «горячей линии» или через электронную форму «задать вопрос», опубликованную на Сайте. Режим работы службы поддержки, номера телефонов &quot;горячей линии&quot; и ссылка на форму обратной связи указаны по адресу - http://www.shopograd.ru/o-shopograde/kontaktnaya-informatsiya/. Не предоставляются консультации по вопросам, не имеющим отношения к Услугам и работе Сайта/Сервиса.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">7.7. Исполнитель обязуется предоставлять доступ к учетной записи пользователя, зарегистрированного на Сайте авторизованным способом в соответствии с условиями, изложенными в Разделе 1 и Разделе 2 Настоящего договора, а также предоставлять доступ к информации, размещенной в Личном Кабинете Пользователя, включая, но не ограничиваясь:<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- данным обо всех заказах, совершенных на Сайте Пользователем с момента его регистрации. При этом, заказы, совершенные пользователем более двух календарных лет с момента текущего обращения к Сайту, доступны в архивированном виде. <o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- информации о движении денежных средств, внесенных Пользователем для оплаты заказа, совершенного на Сайте, включая дату, сумму и метод поступления платежа, а также информацию по расходованию денежных средств по заказу. При этом, информация о движении денежных средств, внесенных Пользователем более двух календарных лет на момент обращения к Сайту, доступна по запросу через Службу Поддержки сайта.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">-иной несущественной информации, предусмотренной условиями работы Сервиса, такой как: товарам, размещенными в разделе &ldquo;Избранное&rdquo;, бонусов, начисленных Сервисом Пользователю в соответствии с условиями маркетинговых и рекламных акций, и другой информации с условием ограниченной ответственности Сервиса по предоставлению данных такого рода.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">8. Другие обязанности и права Покупателя<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.1. Покупатель обязуется своевременно и в полном объеме предоставлять достоверную информацию, необходимую для оказания Услуг Исполнителем. В случае недостатка такой информации или сомнений в ее достоверности Исполнитель имеет право приостановить оказание Услуг, уведомив Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.2. Покупатель обязуется своевременно и в полном объеме оплачивать стоимость заказанных Товаров, а также суммы комиссионного вознаграждения Исполнителя и стоимость доставки Товара до Покупателя. В случае недостаточности средств на лицевом счете Покупателя Исполнитель имеет право приостановить или прекратить обслуживание Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.3. Покупатель обязуется хранить все документы, подтверждающие осуществление платежей в адрес Исполнителя, до зачисления денежных средств на лицевой счет Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.4. Покупатель обязуется предоставить Исполнителю любые данные, подтверждающие легитимность платежа Покупателя, например фотографию или скан банковской карты, а также электронную копию документа, удостоверяющую личность Покупателя с фото. Данные запрашиваются только в исключительных случаях, при возникновении реальных оснований для проверки правомерности платежа, совершенного Покупателем.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.5. Покупатель обязуется ознакомиться с информацией для Покупателей, опубликованной на Сайте, отслеживать в личном кабинете информацию и сообщения о состоянии (статусе) своих заказов и своевременно отвечать на запросы Исполнителя, в том числе если ответ требуется для продолжения оказания Исполнителем Услуг.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.6. Покупатель обязуется сохранять в тайне от третьих лиц свои пароль и логин для авторизации на Сайте и пароль для доступа к электронной почте, сообщенной Исполнителю. Действия, совершенные на Сайте с использованием логина и пароля Покупателя, Стороны признают совершенными Покупателем. Заказы, направленные Исполнителю с использованием Сайта, а также сообщения, направленные с адреса электронной почты Покупателя, сообщенной Исполнителю признаются равнозначными документу, собственноручно подписанному Покупателем.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.7. Покупатель при использовании Сервиса обязан соблюдать законные права и интересы третьих лиц, положения применимого законодательства.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Покупатель обязуется самостоятельно ознакомиться с действующим таможенным законодательством страны доставки и соблюдать его.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Уплата таможенных сборов и пошлин лежит на Покупателе.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.8. Пользователь Сайта не вправе осуществлять в отношении Сайта и Сервиса, их элементов и компонентов воспроизведение (тиражирование и иное копирование), распространение, модификацию, переформатирование и иную переработку. Любые компоненты Сервиса запрещается использовать в составе других сайтов, программных продуктов, других произведений или использовать иным способом. Разрешается просмотр информации и материалов Сайта, исключительно с целью личного некоммерческого использования их воспроизведение в одном экземпляре (в том числе путем копирования в память персонального ЭВМ пользователя, распечатки копии), цитирование в объеме, обусловленном целями цитирования, кроме случаев, когда такое использование причиняет или может причинить вред интересам правообладателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.9. Пользователям Сайта запрещено каким-либо образом причинять вред Сайту и/или Сервису, их пользователям, в том числе (но не ограничиваясь) путем рассылки программных вирусов или иных компьютерных кодов, программ, файлов, направленных на нарушение функциональности любого компьютерного или телекоммуникационного оборудования, их частей, взлома или агрегации любой информации Сервиса, в том числе данных других Пользователей, рассылки «спама» и иной прямо не разрешенной Соглашением информации.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">8.10. Покупатель вправе публиковать на Сайте отзывы о приобретенных Товарах.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">9. Условия возврата и обмена Товара<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.1. В случае возврата/обмена стоимость доставки Товара от Покупателя Исполнителю и от Исполнителя поставщику, а так же в обратных направлениях, оплачивается Покупателем, кроме случаев, когда требование Покупателя о возврате/обмене вызвано ненадлежащим выполнением Исполнителем обязательств по проверке соответствия Товара требованиям Покупателя в соответствии с условиями настоящего Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.2. Исполнитель принимает решение о возможности возврата/обмена Товара, полностью руководствуясь решением поставщика о возможности возврата/обмена. В случае если возврат/обмен Товара не возможен, но при этом Исполнитель ненадлежащим образом выполнил свои обязательства по проверке соответствия Товара требованиям Покупателя, Исполнитель возмещает Покупателю стоимость Товара, Услуг Исполнителя по обработке заказа данного Товара и доставки его Покупателю, а также по усмотрению Исполнителя согласовывает с Покупателем доставку Товара Исполнителю.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.3. В остальных случаях если поставщик принимает решение об отказе Покупателю в возврате/обмене, Исполнитель не компенсирует Покупателю стоимость Товара, а решение о возможности повторной отправки Товара Покупателю принимается Исполнителем на индивидуальной основе с учетом обстоятельств дела.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.4. Все операции по возврату/обмену осуществляются в полном соответствии с условиями поставщика, включая, но не ограничиваясь сроками, процедурой и размером компенсации.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.5. Покупатель должен учитывать сроки доставки Товара от Покупателя Исполнителю, сроки обработки возврата/обмена на складе Исполнителя (до 5 рабочих дней) и сроки доставки Товара от Исполнителя поставщику при расчете возможности возврата/обмена Товаров Продавцу.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.6. При возврате Товара возврат средств Покупателю осуществляется после полного возврата стоимости Товара поставщиком Исполнителю.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">9.7. Комиссионное вознаграждение за оказанные Услуги Исполнителя не возвращается Покупателю независимо от решения поставщика о возможности/невозможности возврата Товара, кроме случаев ненадлежащего исполнения Соглашения Исполнителем (п.1 настоящего раздела).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span style="font-size: 10pt; line-height: 115%; background: white;">9.8. При отправке обмененного Товара Покупатель оплачивает полную стоимость обработки заказа Исполнителем в соответствии с тарифами, указанными на Сайте </span><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">Shopograd</span><span style="font-size: 10pt; line-height: 115%; background: white;">®.<o:p></o:p></span></font></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">10. Ответственность сторон<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><font face="Arial"><span lang="EN-US" style="font-size: 10pt; line-height: 115%; background: white;">10</span><span style="font-size: 10pt; line-height: 115%; background: white;">.1. Стороны несут ответственность за невыполнение Соглашения в случаях, предусмотренных положениями настоящего раздела и других разделов Соглашения, а также применимым правом (раздел 15).<o:p></o:p></span></font></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">10.2. В случае нарушения установленных сроков оказания Услуги Исполнитель уплачивает Покупателю за каждый день просрочки неустойку (пеню) в размере трех процентов цены оказания Услуги, а если цена оказания Услуги договором об оказании Услуг не определена — общей цены заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">При этом сумма взысканной Покупателем неустойки (пени) не может превышать цену отдельного вида оказания Услуги или общую цену заказа, если цена оказания Услуги не определена договором об оказании Услуги.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">10.3. В случае если после оплаты Сервисной услуги Покупатель получит Товар, не соответствующий заявленным характеристикам, Исполнитель выплачивает Покупателю компенсацию в размере стоимости Товара, Услуг (включая Сервисные услуги) и доставки такого Товара.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">10.4. Покупатель при обнаружении недостатков оказанной Услуги вправе по своему выбору потребовать:<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- безвозмездного устранения недостатков оказанной Услуги;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- соответствующего уменьшения цены оказанной Услуги;<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">- возмещения понесенных им расходов по устранению недостатков оказанной Услуги своими силами или третьими лицами.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Удовлетворение требований Покупателя о безвозмездном устранении недостатков или о повторном выполнении оказании Услуги не освобождает Исполнителя от ответственности в форме неустойки за нарушение срока окончания оказания услуги.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Покупатель вправе отказаться от исполнения договора об оказании Услуги и потребовать полного возмещения убытков, если в установленный Соглашением срок недостатки оказанной услуги не устранены Исполнителем. Покупатель также вправе отказаться от исполнения договора об оказании услуги, если им обнаружены существенные недостатки оказанной услуги или иные существенные отступления от условий договора.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Покупатель вправе потребовать также полного возмещения убытков, причиненных ему в связи с недостатками оказанной услуги. Убытки возмещаются в сроки, установленные для удовлетворения соответствующих требований Покупателя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Требования, связанные с недостатками оказанной услуги, могут быть предъявлены при принятии оказанной услуги или в ходе оказания услуги либо, если невозможно обнаружить недостатки при принятии оказанной услуги, в течение 14 дней после получения посылки с Товаром от службы доставки.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Цена оказанной услуги, возвращаемая Покупателю при отказе от исполнения договора об оказании услуги, а также учитываемая при уменьшении цены оказанной услуги, определяется в соответствии с пунктом 2 настоящего раздела.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">10.5. Покупатель и любое третье лицо, не являющееся стороной Соглашения, несут гражданскую, административную или уголовную ответственность в случае незаконного использования интеллектуальной собственности Исполнителя (Сайта и его материалов и компонентов, и Сервиса) и/или нарушения п.8 раздела 8 Соглашения.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">11. Ограничение ответственности Исполнителя<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.1. Исполнитель предоставляет пользователям сети Интернет доступ к Сайту и Сервису и поддерживает надлежащее функционирование Сайта и Сервиса, оперативно восстанавливает их работоспособность в случае технических сбоев и перерывов, при этом не предоставляя гарантий бесперебойной работы Сайта и Сервиса и соблюдения каких-либо сроков восстановления работоспособности Сайта и Сервиса в случае перерывов в работе.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Сервис и Сайт предоставляются на условиях «как есть» (в частности, это означает, что Исполнитель не несет ответственности, связанной с любым искажением, изменением, оптической иллюзией изображений Товаров на Сайте, не обязуется контролировать содержание информации о Товарах и ни при каких обстоятельствах не несет ответственность за соответствие её требованиям законодательства, а также за возможное нарушение прав Покупателей или третьих лиц в связи с использование ими Сайта или Сервиса).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.2. Исполнитель не несет ответственности за любые расходы Покупателя или прямой либо косвенный ущерб, который может быть причинен Покупателю вследствие использования Сайта и/или Сервиса в результате ошибок, пропусков, перерывов в работе, удаления файлов, изменения функций, дефектов, задержек в работе при передаче данных и т.п. Исполнитель не несет ответственности за неисполнение либо ненадлежащее исполнение своих обязательств вследствие сбоев в телекоммуникационных и энергетических сетях, действий вредоносных программ, а также недобросовестных действий третьих лиц, направленных на несанкционированный доступ и/или выведение из строя программного и/или аппаратного комплекса Сервиса.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.3. Исполнитель не несет ответственности за действия смежных служб и сервисов, используемых для предоставления Услуг Покупателю, но не принадлежащих Исполнителю, как то: банки, почтовые службы, интернет-провайдеры, сервисы по оказанию услуг электронной почты, платежные системы и т.д.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.4. Исполнитель не несет ответственности за сроки доставки Товара, отправленного Исполнителю.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.5. Исполнитель не несет ответственности за качество, а также не обеспечивает гарантией Товары, приобретенные в интересах Покупателя по его заказу.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.6. Исполнитель несет ограниченную ответственность за соответствие размера, количества и цвета заказанных товаров: при комплектации посылки Покупателю Исполнитель проверяет только соответствие сведений о количестве, цвете и размере Товара данным на изделии и в заказе. Исполнитель не несет ответственность за несоответствие фактического размера Товара - одежды и обуви - размеру, заявленному на Сайте, если на ярлыках, этикетках, сопроводительных документах к Товару указан размер, соответствующий заказанному.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.7. При выявлении Покупателем явных расхождений по комплектации, размерности и цвету Товара Исполнитель проводит замену таких Товаров только в случае, если возврат и замена Товаров предусмотрена Продавцом. Покупатель обязуется самостоятельно отслеживать информацию о возможности замены Товара, предоставленную Продавцом, в личном кабинете.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.8. Исполнитель сохраняет за собой право изменять содержание, оформление Сайта, изменять или дополнять программное обеспечение, используемые скрипты и другие объекты, используемые или хранящиеся на Сайте, любые серверные приложения в любое время, с/без предварительного уведомления Покупателя. Исполнитель не несет ответственности в случае возникновения у Покупателя в результате внесенных изменений неудобств при пользовании Сайтом или причинения ему какого-либо ущерба.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.9. Исполнитель не несет ответственность за недобросовестность выбранных Покупателем поставщиков в случаях: товар выслан с задержкой; товар выслан, но не соответствует описанию; товар не работающий (хотя заявлен как работающий); товар вообще не выслан (случаи мошенничества).<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.10. Исполнитель не несет ответственности за расчет, взимание таможенных пошлин при доставке посылки и не компенсирует их.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.11. Исполнитель возмещает убытки Покупателя по его заявлению и только в случае, если заявленные убытки явились результатом ошибок, допущенных служащими Исполнителя.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.12. Исполнитель не несет ответственности за любые задержки в ходе доставки заказа, потери или повреждения при доставке заказа, вызванные вмешательством служащих таможни или других государственных органов.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">11.13. Исполнитель не несет ответственности за любые последствия или особые потери или ущерб (включая потерю прибылей, выгоды, рынков, репутации, связанные с использованием содержимого или потерей такой возможности) или другие косвенные убытки, возникающие в связи с потерей, повреждением, задержкой, ошибочной доставкой или недоставкой заказа.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">12. Форс-мажор<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Стороны освобождаются от ответственности за частичное или полное неисполнение обязательств по настоящему Соглашению, если это неисполнение явилось следствием обстоятельств непреодолимой силы, возникших после заключения Соглашения в результате событий чрезвычайного характера, которые участник не мог ни предвидеть, ни предотвратить разумными мерами (форс-мажор). К таким событиям чрезвычайного характера относятся: наводнение, пожар, землетрясение, взрыв, шторм, эпидемия и иные явления природы, а также война или военные действия и т.п.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">13. Разрешение споров<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">13.1. В случае возникновения разногласий и споров, связанных с выполнениями условия данного Соглашения, стороны решают их путем переговоров.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">13.2. В случае невозможности решения споров путем переговоров споры разрешаются в порядке, установленном законодательством Шотландии.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" align="center" style="text-align: justify;"><b><span style="line-height: 115%; background: white;"><font face="Arial">14. ПРОЧИЕ УСЛОВИЯ<o:p></o:p></font></span></b></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">14.1. Исполнитель оставляет за собой право в одностороннем порядке и без предварительного уведомления Покупателей изменять условия Соглашения, разместив при этом окончательную версию Соглашения на странице по адресу http://www.shopograd.ru/o-shopograde/publichnaya-oferta/ за 10 (десять) дней до вступления изменений в силу. Положения новой редакции Соглашения становятся обязательными для всех ранее зарегистрировавшихся пользователей Сайта.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">14.2. Настоящее Соглашение ни при каких обстоятельствах не может быть трактовано как договор об установлении агентских отношений, отношений товарищества, отношений по совместной деятельности, отношений личного найма, либо каких-то иных отношений между Покупателем и Исполнителем, прямо не указанных в настоящем Соглашении.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">14.3. Настоящее Соглашение, а также все споры и претензии, вытекающие из него или связанные с ним или основанные на нем (в том числе внедоговорные споры или претензии), регулируются и толкуются в соответствии с законодательством Шотландии без учета коллизии правовых норм.<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Адрес размещения в сети Интернет: http://www.shopograd.ru/o-shopograde/publichnaya-oferta/<o:p></o:p></font></span></p>
 
<p class="MsoNormal" style="text-align: justify;"><span style="font-size: 10pt; line-height: 115%; background: white;"><font face="Arial">Дата: 01 января 2015 г.</font><font face="Arial, sans-serif"><o:p></o:p></font></span></p>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>