<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?=$arResult['DETAIL_TEXT']?>
<?if($arResult['DISPLAY_PROPERTIES']['PRODUCT']['DISPLAY_VALUE'] or $arResult['DISPLAY_PROPERTIES']['PRODUCT_NAME']['DISPLAY_VALUE']):?>
	<p><b>Товар:</b> <?if($arResult['DISPLAY_PROPERTIES']['PRODUCT']['DISPLAY_VALUE']):?><?=$arResult['DISPLAY_PROPERTIES']['PRODUCT']['DISPLAY_VALUE']?><?else:?><?=$arResult['DISPLAY_PROPERTIES']['PRODUCT_NAME']['DISPLAY_VALUE']?><?endif;?></p>
<?endif;?>
<p><b>Дата получения заказа:</b> <?=FormatDate('j F Y', strtotime($arResult['DATE_CREATE']));?></p>
<p><b>Дата публикации отзыва:</b> <?=FormatDate('j F Y', strtotime($arResult['TIMESTAMP_X']));?></p>
<?
global $arMoreReviewsFilter;
$arMoreReviewsFilter = array('PROPERTY_USER'=>$arResult['DISPLAY_PROPERTIES']['USER']['VALUE'], '!ID'=>$arResult['ID']);
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"reviews",
	Array(
		"IBLOCK_TYPE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["IBLOCK_TYPE"],
		"IBLOCK_ID"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["IBLOCK_ID"],
		"NEWS_COUNT"	=>	"30",
		"SORT_BY1"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["SORT_BY1"],
		"SORT_ORDER1"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["SORT_ORDER1"],
		"SORT_BY2"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["SORT_BY2"],
		"SORT_ORDER2"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["SORT_ORDER2"],
		"FIELD_CODE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["LIST_FIELD_CODE"],
		"PROPERTY_CODE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["LIST_PROPERTY_CODE"],
		"DETAIL_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
		"SECTION_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
		"IBLOCK_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["news"],
		"DISPLAY_PANEL"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["DISPLAY_PANEL"],
		"SET_TITLE"	=>	"N",
		"SET_STATUS_404" => $arParams['_COMPLEX_COMPONENT_PARAMS']["SET_STATUS_404"],
		"INCLUDE_IBLOCK_INTO_CHAIN"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["INCLUDE_IBLOCK_INTO_CHAIN"],
		"CACHE_TYPE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["CACHE_TYPE"],
		"CACHE_TIME"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["CACHE_TIME"],
		"CACHE_FILTER"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["CACHE_FILTER"],
		"CACHE_GROUPS" => $arParams['_COMPLEX_COMPONENT_PARAMS']["CACHE_GROUPS"],
		"DISPLAY_TOP_PAGER"	=>	"N",
		"DISPLAY_BOTTOM_PAGER"	=>	"N",
		"PAGER_TITLE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_TITLE"],
		"PAGER_TEMPLATE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_TEMPLATE"],
		"PAGER_SHOW_ALWAYS"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_SHOW_ALWAYS"],
		"PAGER_DESC_NUMBERING"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_DESC_NUMBERING"],
		"PAGER_DESC_NUMBERING_CACHE_TIME"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_DESC_NUMBERING_CACHE_TIME"],
		"PAGER_SHOW_ALL" => $arParams['_COMPLEX_COMPONENT_PARAMS']["PAGER_SHOW_ALL"],
		"DISPLAY_DATE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["DISPLAY_DATE"],
		"DISPLAY_NAME"	=>	"Y",
		"DISPLAY_PICTURE"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["DISPLAY_PICTURE"],
		"DISPLAY_PREVIEW_TEXT"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["DISPLAY_PREVIEW_TEXT"],
		"PREVIEW_TRUNCATE_LEN"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["PREVIEW_TRUNCATE_LEN"],
		"ACTIVE_DATE_FORMAT"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["LIST_ACTIVE_DATE_FORMAT"],
		"USE_PERMISSIONS"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["USE_PERMISSIONS"],
		"GROUP_PERMISSIONS"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["GROUP_PERMISSIONS"],
		"FILTER_NAME"	=>	'arMoreReviewsFilter',
		"HIDE_LINK_WHEN_NO_DETAIL"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["HIDE_LINK_WHEN_NO_DETAIL"],
		"CHECK_DATES"	=>	$arParams['_COMPLEX_COMPONENT_PARAMS']["CHECK_DATES"],
        
        "_TITLE" => "Другие отзывы пользователя"
	),
	false
);?>